### ISSUE TITLE
Bootstrap with offline version?

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#105]
The bootstrap feature is quite cool, but it renders any superbuild vulnerable to any shortage of any 3rd party repo referenced by YCM (see https://github.com/robotology/ycm/issues/103).
Could it make sense to bootstrap using the offline version of YCM ?

**Comment by drdanz** [comment]
I need to think about this... The idea of the bootstrap phase is that together with the other repositories you can manage also YCM git repository.

On the other hand it makes sense to not make it break in case some repository is not reachable or changes location...

**Comment by traversaro** [comment]
Related: https://github.com/robotology/ycm/issues/113  (even if in this cased it was caused by a Gitlab downtime).

**Comment by traversaro** [comment]
To anyone having the same problem: use the offline version of ycm available at https://github.com/robotology/ycm/releases .

**Comment by traversaro** [comment]
Related issue: https://github.com/robotology/ycm/issues/172 .

**Comment by drdanz** [comment]
Starting from the next release, along with the `-offline` version that should be used for packaging, I will add a `YCM-<ver>-all.tar.gz` file that will contain the "binary" release, that can probably be used with `FetchContent`

**Comment by PeterBowman** [comment]
> The bootstrap feature is quite cool, but it renders any superbuild vulnerable to any shortage of any 3rd party repo referenced by YCM

This is particularly annoying since 3rd-party UseLatex.cmake module was introduced in YCM v0.10. I managed to reproduce and inspect [this error](https://travis-ci.org/roboticslab-uc3m/openrave-yarp-plugins/jobs/526210662#L1121) locally - the downloaded file is either incomplete or empty. Note that we don't bootstrap YCM itself, this happens on a cloned YCM repository, during the build phase.
