### ISSUE TITLE
file DOWNLOAD HASH mismatch error

### ISSUE THREAD

**Issue by liesrock** [robotology/ycm#108]
In the robotology-superbuild we are having a problem related with file DOWNLOAD HASH mismatch, here the details:

- Downloading CMakeParseArguments.cmake - Attempt 1 of 3
CMake Error at cmake/IncludeUrl.cmake:281 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/lucamuratore/test-superbuild/build/CMakeFiles/CMakeParseArguments.cmake]
      expected hash: [0c4d3f7ed248145cbeb67cbd6fd7190baf2e4517]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [22;"HTTP response code said error"]

It did not appear in the past: what do you think @drdanz, @traversaro ?

**Comment by traversaro** [comment]
Mhh.. there is a way to reproduce the issue? I guess with Ubuntu 14.04 + CMake 3.5 built from source?

**Comment by liesrock** [comment]
It is both 16.04 + default CMake 3.5 and 14.04 + CMake 3.5 binaries.
if you just 
```
git clone https://github.com/robotology-playground/robotology-superbuild.git test-superbuild
cd test-superbuild && mkdir build && cd build
cmake ..
```
You can see the error.

**Comment by traversaro** [comment]
I get it, it happens in all *newly* create build directories. 
I added some info to the error: 
~~~
~~~

**Comment by traversaro** [comment]
The problem is this recent commit: https://github.com/robotology/ycm/commit/8275d2e42605c0cee9d1573249879bd51f8773d4 that changed the location of `cmake-next/Modules/CMakeParseArguments.cmake` to   various version-specific location. I thin that for CMake 3.5 the easiest fix is to avoid donwload that file, given that is not necessary, but I have to understand where this information is encoded.

**Comment by traversaro** [comment]
`_ycm_include`  https://github.com/robotology/ycm/blob/19fd29340a08e03757947cf59c111cf68aaf44d9/modules/YCMEPHelper.cmake#L94 is the macro to fix.
