### ISSUE TITLE
Update FindGLFW3.cmake to support the latest version installed from vcpkg

### ISSUE THREAD

**Issue by traversaro** [robotology/ycm#133]
In https://github.com/robotology/yarp/issues/1675 , @mebbaid observed problem with the `FindGLFW3.cmake` script shipped with YCM when used with the latest `glfw3` installed by vcpkg. We should check if it needs to be updated. 

@mebbaid can you provide the details of your modification to the `FindGLFW3.cmake` file? Thanks

**Comment by traversaro** [comment]
By the way, as the latest `glfw3` install its own `glfw3Config.cmake` file that exposes the `glfw` imported target. it could make sense to add in the `FindGLFW3.cmake` a call to `find_package(glfw3 CONFIG)` and, if the `glfw` imported target is defined, define `GLFW3_INCLUDE_DIRS`, `GLFW3_LIBRARIES` and `GLFW3::GLFW3` from the data in the `glfw` imported target. 
Unfortunately just drop the `FindGLFW3.cmake` script  until we support Ubuntu 16.04, as in this system `glfw3Config.cmake` does not define the `glfw` imported target.

cc @drdanz @claudiofantacci

**Comment by mebbaid** [comment]
@traversaro : yeah, the thing is, when you install the package using `vcpkg install --triplet x64-windows glfw3` , this part of `FindGLFW3.cmake`:
```
if(NOT GLFW3_FOUND)
  find_path(GLFW3_INCLUDE_DIR
            DOC "Path to GLFW3 include directory."
            NAMES GLFW/glfw3.h
            PATH_SUFFIXES include
            PATHS /usr/
                  /usr/local/
                  ${GLFW3_ROOT_DIR}
                  ENV GLFW3_ROOT)
find_library(GLFW3_GLFW_LIBRARY
              DOC "Absolute path to GLFW3 library."
              NAMES glfw3
                    glfw3dll
              PATH_SUFFIXES lib
                            lib-vc2010
              PATHS /usr/
                    /usr/local/
                    ${GLFW3_ROOT_DIR}
                    ENV GLFW3_ROOT)
....
```
is not executed, since `GLFW FOUND TRUE` because it is there in the standard `CMAKE_PREFIX_PATH`. however this means `GLFW3_GLFW_LIBRARY` will return `NOT_FOUND` and then when you generate the solution, and try to build it, the linker will not be able to open this `GLFW3_GLFW_LIBRARY.obj` thingy, which is supposed to point at `glfw3dll.lib` as far as i understand it. maybe more expert people can chime in, however what I did was to simply use `if( GLFW3_FOUND)` as well.

**Comment by traversaro** [comment]
I think https://github.com/robotology/ycm/pull/135 should fix this issue, by defining `GLFW3::GLFW3` as an alias of `glfw` in case the imported target `glfw` is defined.

**Comment by drdanz** [comment]
Is the `glfw` target coming from upstream or from vcpkg?

**Comment by drdanz** [comment]
In this case we should make a patch to add the namespace to their target :tired_face:

**Comment by randaz81** [comment]
I have problems with glfw3 (clean installation).
Can you please tell me more abour the status of this issue? Can I use (and merge) #135?
