### ISSUE TITLE
Bump CMake Requirement

### ISSUE THREAD

**Issue by drdanz** [robotology/ycm#261]
According to [our policies](https://wiki.icub.org/wiki/YARP_Supported_Distributions), we can now drop CMake 3.5 on the devel branch.

I'd like to require at least CMake 3.11, but, unfortunately:

1) Debian stretch (oldstable) has CMake 3.7.2.
2) Ubuntu bionic 18.04 LTS has CMake 3.10.2.

If we consider our current policies we should switch to 3.7. Not really a big advantage (probably nothing at all). Also considering that, when we'll make the next release, stretch will no longer be supported, I think we can drop support right now. Stretch users can easily install 3.13.2 is in the backports repository.

If we drop support for debian oldstable, we can decide at least for CMake 3.10

Since CMake 3.11 introduce some very important changes, I'd like to require at least that version. This means that bionic would not work out of the box, though. There is a new [CMake apt repository](https://apt.kitware.com/) managed by Kitware for ubuntu LTS that has CMake 3.15. We could require that all bionic users install CMake from that repository. Unfortunately bionic is also on the robot. Anyway, consider that is a lot easier to do this, compared to do workarounds like this useless set of patches (6056bae91c34ad78608b05e1790562de07855195 + e57721f7353d83788b551f7c575c0163adca6ef4 + 5dbda4df81a93545ee2036d02bcf79bd8194e5e9 + 60548f10f6f276672d9b7d7fd38f2e85689230dc + e1f6d476905906651f7c8be6937cff4a7bf33581) that took me almost a week to fix, and forced me to make a new release.

If we disregard stretch and bionic, we can actually switch to 3.12, that is supported by all the other supported releases, and introduces another important set of changes.

So the options are
- :-1: **3.7**
- :confused: **3.10**
- :+1: **3.11**
- :rocket: **3.12**

This is an important decision because it will impact the robots, and all the other repositories, therefore we need to discuss this.

cc @lornat75 @pattacini @vtikha @traversaro @Nicogene @aerydna

**Comment by Nicogene** [comment]
> There is a new CMake apt repository managed by Kitware for ubuntu LTS that has CMake 3.15. We could require that all bionic users install CMake from that repository. Unfortunately bionic is also on the robot. 

Add a source to apt/source.list I don't think it is a big trouble, we have to add it in the installation instruction as requirement.

**Comment by traversaro** [comment]
I am not a big fan of requiring newer non-system versions of system dependencies, because typically this drastically complicates the use of a project combined together with other projects that also require (typically different) newer non-system version of system dependencies (Tensorflow and similar are a good example of this kind of patterns).

However, considering that:
* the alternative is to spend weeks of work
* CMake is just a **build** dependency, so you can always use a local newer version to build and then deploy the binary artifacts 
* use of the Kitware apt repository means (if I am not mistaken) that system `apt` packages that depend on cmake will not be broken if we use a more recent cmake 
* as soon as Ubuntu 20.04 is released, we go back to use system CMake  
* `FetchContent` (contained in CMake 3.11) is really great
* CMake is just a tool, and CMake developers make sure that the internals are never exposed for example as shared library

I think I can agree with requiring CMake 3.12 .

**Comment by PeterBowman** [comment]
On a side note, Ubuntu 16.04 (Xenial) images on Travis CI use CMake 3.12.4 ([ref](https://docs.travis-ci.com/user/reference/xenial/#compilers-and-build-toolchain)).

**Comment by drdanz** [comment]
For reference, it was decided to make an exception and go for CMake 3.12.

**Comment by drdanz** [comment]
Closed by #285
